### PR TITLE
AddFile.Feature

### PR DESCRIPTION
**Pull request by Sorin1991**

### CODE REVIEW

**Review by ulkucardak — COMMENTED** [review]
Hi Sorin. If It is ok for you, you can change your step definition's class name from 'Files_page' to 'FilesPage_Step_Defs'. Because it is very similar pages class name and it might be confusing sometimes. And in your feature file, I saw some steps for login but I did not see their code in the step_defs class. Ariane created a method for login. you can use it from LoginBasePage.

**Comment by NikolasTonic** [comment]
Good point from Ulku

**Review by NikolasTonic — APPROVED** [review]

**Review by ulkucardak — APPROVED** [review]

**Comment by Sorin1991** [comment]
hello

**Review by cemalpolat — APPROVED** [review]

**Review by ulkucardak — APPROVED** [review]

**Comment by cemalpolat** [comment]
OK

**Pull request merged**
