### PR TITLE
completed @CLOUD-513 logout US

### PR DESCRIPTION
**Pull request by NadiaNawazx**

### CODE REVIEW

**Review by arianestoll — APPROVED** [review]
step definitions for log out scenario and add new contact scenario look all sound to me. 
You'll do the step def for Talk functionality later, right? Or they somewhere there and I've missed them?
Thanks for adding the camel snippet thingy!

**Review by cemalpolat — APPROVED** [review]

**Review by cemalpolat — APPROVED** [review]

**Review by cemalpolat — APPROVED** [review]

**Review by ulkucardak — COMMENTED** [review]
You worked very hard Nadia! I reviewed most of them. But not step by step. Are all of them working properly? I just realised one thing, in the DeckFunction feature file, there is Scenario Outline and I could not see its step defs. Could you please check?

**Comment by NadiaNawazx** [comment]
> step definitions for log out scenario and add new contact scenario look all sound to me. You'll do the step def for Talk functionality later, right? Or they somewhere there and I've missed them? Thanks for adding the camel snippet thingy!

talk func is Ayse, not sure why it came up in my list? maybe i was browsing it and hit space not sure!

**Comment by NadiaNawazx** [comment]
> 

Ulku, Deck is all complete and tested passed

**Pull request closed without merging**
