### PR TITLE
SorinBranch_day1

### PR DESCRIPTION
**Pull request by Sorin1991**
My work on addFiles

### CODE REVIEW

**Comment by ulkucardak** [comment]
Hi Sorin, I think you closed the pull request. I looked at your code but I didn't understand that how did you verified or make assertion about uploading file.

**Review by Sorin1991 — COMMENTED** [review]
I completed my AddFiles US

**Review by cemalpolat — COMMENTED** [review]
@When("user click upload files option from dropDown")
    public void user_click_upload_files_option_from_drop_down() {
        Assert.assertTrue(filePage.uploadFilesButton.isDisplayed());
where did you clicked here? There is only assertion of the displaying of the upload files option.

**Comment by cemalpolat** [comment]
At the end, how did you checked that the uploaded file is on the page? There is no code for it I think

**Comment by ulkucardak** [comment]
Sorin, Cemal said that where is the click action but  I know and we talked about it. you should not click before sending the path. your code is ok. 
when("user click upload files option from dropDown")
public void user_click_upload_files_option_from_drop_down() 
But you can change this step sentence to "user should see upload file option"

**Review by Sorin1991 — COMMENTED** [review]
I done changes

**Review by ulkucardak — APPROVED** [review]

**Pull request closed without merging**
